### ISSUE TITLE
Getting this error Kindly Check How can we solve this error?

### ISSUE THREAD

**Issue by muazamaliofficial** [bhackel/cheggbog#2]
![Screenshot_327](https://user-images.githubusercontent.com/55577898/152100138-63969344-c470-4b99-bc44-fee93582802d.png)

**Getting this error Kindly Check How can we solve this error?**

**Comment by bhackel** [comment]
This happens when the python script cannot find the screenshot file to upload. I would check to make sure that you followed all the directions, especially the stuff related to setting up the GoFullPage extension. Also, make sure you change the path = "C:/Users/[YOUR USERNAME]/Downloads/screenshots/*" in the file to be your username (in your case, its Administrator). If none of this works, try running the script with administrator privileges, as Windows Server can have issues with that. Also, there is a known bug I haven't bothered to fix where large Chegg links cause the bot to close the tab before it downloads, so that's another possibility.

**Comment by muazamaliofficial** [comment]
It works for 1 time then when next time it runs its like it doesn't take screenshot all permissions are given and also I have increased the sleeping time to 15 sec to avoid to close it before it downloads...

I think keypress might not be working if there is any alternative kindly update me thanks

**Comment by TresorChun** [comment]
> This happens when the python script cannot find the screenshot file to upload. I would check to make sure that you followed all the directions, especially the stuff related to setting up the GoFullPage extension. Also, make sure you change the path = "C:/Users/[YOUR USERNAME]/Downloads/screenshots/*" in the file to be your username (in your case, its Administrator). If none of this works, try running the script with administrator privileges, as Windows Server can have issues with that. Also, there is a known bug I haven't bothered to fix where large Chegg links cause the bot to close the tab before it downloads, so that's another possibility.

can we talk private?

**Comment by bhackel** [comment]
> It works for 1 time then when next time it runs its like it doesn't take screenshot all permissions are given and also I have increased the sleeping time to 15 sec to avoid to close it before it downloads...
> 
> I think keypress might not be working if there is any alternative kindly update me thanks

Yeah if that's the issue then I'm not sure what to do about it, you could try using mouse position inputs to run the extension instead, but I can't be bothered to write that unfortunately.

**Comment by bhackel** [comment]
> > This happens when the python script cannot find the screenshot file to upload. I would check to make sure that you followed all the directions, especially the stuff related to setting up the GoFullPage extension. Also, make sure you change the path = "C:/Users/[YOUR USERNAME]/Downloads/screenshots/*" in the file to be your username (in your case, its Administrator). If none of this works, try running the script with administrator privileges, as Windows Server can have issues with that. Also, there is a known bug I haven't bothered to fix where large Chegg links cause the bot to close the tab before it downloads, so that's another possibility.
> 
> can we talk private?

Sure if you want to

**Comment by TresorChun** [comment]
> > > This happens when the python script cannot find the screenshot file to upload. I would check to make sure that you followed all the directions, especially the stuff related to setting up the GoFullPage extension. Also, make sure you change the path = "C:/Users/[YOUR USERNAME]/Downloads/screenshots/*" in the file to be your username (in your case, its Administrator). If none of this works, try running the script with administrator privileges, as Windows Server can have issues with that. Also, there is a known bug I haven't bothered to fix where large Chegg links cause the bot to close the tab before it downloads, so that's another possibility.
> > 
> > 
> > can we talk private?
> 
> Sure if you want to

email me your discord ID at streetdadserver@gmail.com
