### ISSUE TITLE
error

### ISSUE THREAD

**Issue by avtar312** [bhackel/cheggbog#5]
file_loc = max(glob.glob(path, recursive=True), key=os.path.getmtime)
ValueError: max() arg is an empty sequence

**Comment by avtar312** [comment]
file_loc = max(glob.glob(path, recursive=True), key=os.path.getmtime)
ValueError: max() arg is an empty sequence

**Comment by bhackel** [comment]
Yeah this happens when the program doesn't wait long enough for the screenshot to finish. You can increase the delays on lines 44 and 46 as a temporary solution until I get around to fixing it.

**Comment by avtar312** [comment]
ok thanku

**Comment by avtar312** [comment]
Can u add cookie method for login account

**Comment by bhackel** [comment]
Probably not, 1 its unreliable, 2 I would have to learn how to implement it, 3 I wouldn't have a use for it, 4 it's pretty much the same as logging in

**Comment by avtar312** [comment]
When I put bot on rdp server it only open link and not take screen shot can u help

**Comment by bhackel** [comment]
The problem could be many things, you can try running the python script as administrator, make sure the screenshot extension is properly installed, make sure chrome is the selected window when the bot is running

**Comment by avtar312** [comment]
How to select chrome browser to open link it open on Microsoft browser only. Please help

**Comment by bhackel** [comment]
You probably need to set the default browser in windows default app settings

**Comment by avtar312** [comment]
Thanku so much

**Comment by avtar312** [comment]
Can i see your bot server..? Your bot working on server

**Comment by bhackel** [comment]
What do you want to see about it? I can't just show you the whole thing.

**Comment by avtar312** [comment]
Rdo server not allow to take screen shot?

**Comment by bhackel** [comment]
I have no idea, I'm using a virtual machine for mine

**Comment by avtar312** [comment]
> I have no idea, I'm using a virtual machine for mine

i think it not work on server, remote server not allow to take screenshot

**Comment by bhackel** [comment]
Fixed the file not found error in the latest version
