### ISSUE TITLE
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by maxorion411** [bhackel/cheggbog#6]
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

you can see image below
![image](https://user-images.githubusercontent.com/62614519/188790161-55c73b83-9109-46e1-93bb-c5b7586d98f8.png)

**Comment by bhackel** [comment]
Oh fun lemme fix that easy

**Comment by bhackel** [comment]
Should be fixed in the latest update, let me know if there are any further issues.

**Comment by maxorion411** [comment]
![image](https://user-images.githubusercontent.com/62614519/188798631-0227a0d7-3142-4e5d-a48b-b8333faa12be.png)

can run but bot is not responding

**Comment by bhackel** [comment]
Might need to give the bot message read, react, and file attachment permissions. You will need to create a new bot invite link and re-add it to the server. If this is a direct message, then it's probably something else, not entirely sure. You can test it by sending the links in a direct message to the bot.

**Comment by bhackel** [comment]
nvm it's my bad working on a fix

**Comment by bhackel** [comment]
Fixed in latest update, let me know if anything else is broken
